version: '4.7.0'

services:
  # PostgreSQL
  postgres:
    container_name: postgres
    env_file:
      - ./.env 
    build: ./postgres
    ports:
      - "5431:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # Backend
  face-rec-api:
    container_name: backend
    env_file:
      - ./.env
    build: ./
    volumes:
      - ./:/usr/src/face-rec-api
    command: npm start
    ports:
      - "3000:3000"